USER_APP_OBJS =	output/userApp/main.o \
                output/userApp/shell.o \
                output/userApp/memTestCase.o \
                output/userApp/schedulerTestCasesFCFS.o \
                output/userApp/schedulerTestCasesRR.o \
                output/userApp/schedulerTestCasesPrio.o \
                output/userApp/schedulerTestCasesSJF.o
