SCHEDULER_OBJS = output/myOS/kernel/scheduler/scheduler.o \
				 output/myOS/kernel/scheduler/schedulerFCFS.o \
				 output/myOS/kernel/scheduler/schedulerRR.o \
				 output/myOS/kernel/scheduler/schedulerPrio.o \
				 output/myOS/kernel/scheduler/schedulerSJF.o