# 不需要修改
include $(SRC_RT)/myOS/dev/Makefile
include $(SRC_RT)/myOS/i386/Makefile
include $(SRC_RT)/myOS/printk/Makefile

MYOS_OBJS =	output/myOS/start32.o output/myOS/osStart.o\
			${DEV_OBJS} \
			${I386_OBJS} \
			${PRINTK_OBJS}
