include $(SRC_RT)/myOS/kernel/mem/Makefile
include $(SRC_RT)/myOS/kernel/scheduler/Makefile
include $(SRC_RT)/myOS/kernel/task/Makefile
include $(SRC_RT)/myOS/kernel/time/Makefile

KERNEL_OBJS = ${MEM_OBJS} \
			  ${SCHEDULER_OBJS} \
			  ${TASK_OBJS} \
			  ${TIME_OBJS}
