include $(SRC_RT)/myOS/dev/Makefile
include $(SRC_RT)/myOS/i386/Makefile
include $(SRC_RT)/myOS/kernel/Makefile
include $(SRC_RT)/myOS/printk/Makefile
include $(SRC_RT)/myOS/lib/Makefile

MYOS_OBJS =	output/myOS/start32.o output/myOS/osStart.o \
            ${DEV_OBJS} \
			${I386_OBJS} \
			${PRINTK_OBJS} \
			${KERNEL_OBJS} \
			${LIB_OBJS}
